INHERIT: ../../mkdocs-base.yml
site_name: Pianola
site_description: ğŸ¹ World's finest piano roll visualizer, where elegance meets motion
site_url: https://pianola.brokensrc.dev/
repo_url: https://github.com/BrokenSource/Pianola/
nav:
  - Home:
    - index.md
  - Installation:
    - get/index.md
    - ğŸ“¦ Installers: get/installers.md
    - ğŸ§€ Wheels: get/wheels.md
    - ğŸ”¥ Source: get/source.md
  - Usage:
    - quickstart/index.md
    - ğŸ”´ Gradio WebUI: webui.md
    - ğŸŸ¡ Command line: commands.md
    - ğŸŸ¢ Python scripts: scripts.md
  - Documentation:
    - docs/index.md
  - Code:
      - ğŸ“¦ Package: code/pianola/
theme:
  custom_dir: ../../Website/overrides
