INHERIT: ../../mkdocs-base.yml
site_name: Pianola
site_description: ðŸŽ¹ World's finest piano roll visualizer, where elegance meets motion
site_url: https://pianola.brokensrc.dev/
repo_url: https://github.com/BrokenSource/Pianola/
nav:
  - Home:
    - index.md
  - Installation:
    - get/index.md
    - ðŸ“¦ Installers: get/installers.md
    - ðŸ§€ Wheels: get/wheels.md
    - ðŸ”¥ Source: get/source.md
  # - Documentation:
  #   - docs/index.md
  # - Code:
  #   - ðŸ“¦ Package: Code/
theme:
  custom_dir: ../../Website/overrides
  favicon: Pianola/Resources/Images/Pianola.png
markdown_extensions:
  pymdownx.snippets:
    base_path: [../../Website]
